### ISSUE TITLE
What should we do if they don't have GPG setup?

### ISSUE THREAD

**Issue by futurepaul** [futurepaul/signed-address-generator#18]
There should probably be some nice fallback where we point them at a resource so they know how to set up GPG and create a key.

**Comment by 6102bitcoin** [comment]
Good Guide: https://medium.com/@acparas/gpg-quickstart-guide-d01f005ca99

**Comment by 6102bitcoin** [comment]
Generate a Key
```
gpg --full-generate-key
```

Get Fingerprint to put in twitter bio
```
gpg --list-secret-keys --fingerprint
```

Get Public PGP Key to put on website
```
gpg --armor --export <key ID>
```
