### ISSUE TITLE
Bug: JSON Path with commas fails

### ISSUE THREAD

**Issue by 6102bitcoin** [futurepaul/signed-address-generator#4]
When setting up a new address factory the user is prompted for the path to the .json file

If a user drags a file into the terminal the path is specified like this `/home/....json` which causes the script to end with `Error: No such file or directory (os error 2)`.

Solution: Remove leading and trailing `'` from the entered path?

**Comment by futurepaul** [comment]
This should be fixed as of https://github.com/futurepaul/signed-address-generator/pull/3/commits/7e6bc8aded519099e5ddb037fe28cc2b99e12b1c
