### ISSUE TITLE
Suggestion: address-factory.json filename

### ISSUE THREAD

**Issue by 6102bitcoin** [futurepaul/signed-address-generator#5]
Currently a new address factory always gets named address-factory.json and is saved in the root directory of the program files. 

Suggestions:
- [ ] Prefix with date of creation (as used when generating the signed_addresses.db) 
- [ ] Let user specify name of address-factory and add as a suffix (before .json)
- [ ] Let user specify whether to save file in root of program, in same directory as imported .json or on another location (complex to implement)

E.g. 2021-02-22_address-factory_coldcardtest.json

**Comment by futurepaul** [comment]
I'm a little reticent to do number 3 because we don't have nice path editing and autocomplete that people usually have when typing paths in the terminal. but the other 2 sound straighforward

**Comment by futurepaul** [comment]
@6102bitcoin does #10 fix this? or do we still want versioning inside the config folder

**Comment by 6102bitcoin** [comment]
Ignore this for now

**Comment by 6102bitcoin** [comment]
I don't know how you would easily manage multiple donation configs with the current setup - but we can look at this later
