### ISSUE TITLE
Suggestion: Importing address-factory.json

### ISSUE THREAD

**Issue by 6102bitcoin** [futurepaul/signed-address-generator#6]
User may have never moved the address-factory.json file that was generated when initialising. In this case, they don't know where the address-factory.json file is.

Suggestion:
- [] Look in the root directory of program for any address-factory.json files and present to the user for selection
- [] Have a folder of address-factory.json files rather than storing in the root of the program

**Comment by futurepaul** [comment]
I think #10 covers this, feel free to re-open if not
