### ISSUE TITLE
Suggestion: Persistent Files / Paths

### ISSUE THREAD

**Issue by 6102bitcoin** [futurepaul/signed-address-generator#8]
Maybe we could make a .addressfactory directory in the home folder which is where the address-generator.json files are stored. This way they would be easy to keep track of, and could be called from various versions of the software.

**Comment by futurepaul** [comment]
I believe the convention on Linux / Unix is to put this in the .config folder but I don't know about Windows. (Also I haven't tested this on Windows at all)
